import streamlit as st
from streamlit_image_coordinates import streamlit_image_coordinates
from PIL import Image, ImageDraw
import time
import io
import datetime
from zoneinfo import ZoneInfo
import requests
import base64
import pandas as pd


# ------------------------------------------------------------------
# 🔗 CONFIGURATION: Power Automate Endpoints
# ------------------------------------------------------------------
POWER_AUTOMATE_URL = "https://default9b2f9cbe865b4df8a5848494d8c1ef.f6.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/47ed5cfbda7d44a3a9ca56f439adaac0/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=QbnMaks1c-bPXRhe7oHTfnKKO_6PdN48H5AvoV1qdYU"
EXCEL_FETCH_URL = "https://default9b2f9cbe865b4df8a5848494d8c1ef.f6.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/1cada14a49c94756afd2dfa3079ce584/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=eRGiFPth2frXt9B3k9PNGkmSFyf45-bq7fAw-6AniZc" 

st.set_page_config(page_title="AGS Roof Leak Master Mapper", layout="wide")
st.title("🏭 AGS Roof Leak Tracking Tool")
st.info("💡Select plant from the dropdown and enter your AGS email. Then click anywhere on the **floor map** image to plot a leak. Scroll down to to edit more details and submit a report.")

# --- ENGINE: Advanced Hover Magnification CSS ---
st.markdown("""
    <style>
        /* Define the frame layout container */
        .zoom-lens-container {
            position: relative;
            overflow: hidden;
            border: 2px solid #003366;
            border-radius: 6px;
            cursor: crosshair !important;
            width: 100%;
        }

        /* Target the internal canvas component generated by Streamlit image coordinates */
        .zoom-lens-container div[data-testid="stDataFrameDynamicRender"] img,
        .zoom-lens-container canvas,
        .zoom-lens-container img {
            transition: transform 0.15s ease-out;
            transform-origin: center center;
        }

        /* --- THE MAGIC HOVER TRIGGER --- */
        /* When the mouse hovers inside the container, scale up by 2.2x magnification */
        .zoom-lens-container:hover div[data-testid="stDataFrameDynamicRender"] img,
        .zoom-lens-container:hover canvas,
        .zoom-lens-container:hover img {
            transform: scale(2.2);
        }
    </style>
    
    <script>
        // Track the cursor movement to continuously shift the zoom center focus dynamically
        document.addEventListener('mousemove', function(e) {
            const container = e.target.closest('.zoom-lens-container');
            if (!container) return;
            
            const target = container.querySelector('canvas') || container.querySelector('img');
            if (!target) return;
            
            const rect = container.getBoundingClientRect();
            const x = ((e.clientX - rect.left) / rect.width) * 100;
            const y = ((e.clientY - rect.top) / rect.height) * 100;
            
            target.style.transformOrigin = `${x}% ${y}%`;
        });
    </script>
""", unsafe_allow_html=True)

# 1. User & Plant Info Inputs
col_p1, col_p2 = st.columns([4.0, 6.0])
with col_p1:
    plant = st.selectbox("Select Plant:", ['Cambridge - 07', 'Oshawa - 04', 'Sterling South', 'Windsor - 02'])
    plant_key = plant.replace(' ', '_').replace('-', '_')
    
    # Simple checkbox icon control feature to turn the magnifying engine on/off
    enable_lens = st.checkbox("🔍 Enable Interactive Precision Zoom Lens", value=True)
    
with col_p2:
    user_email = st.text_input("📋 Enter your AGS Automotive Email:", placeholder="username@agsautomotive.com").strip().lower()

is_email_valid = user_email.endswith("@agsautomotive.com") and len(user_email) > 18

if "new_pins_batch" not in st.session_state or st.session_state.get("current_active_plant") != plant:
    st.session_state["current_active_plant"] = plant
    st.session_state["new_pins_batch"] = []

# Weather Engine Functionality
@st.cache_data(ttl=3600)
def get_real_weather_data(plant_name, target_date):
    coordinates = {
        'Cambridge - 07': {"lat": 43.403449, "lon": -80.322832},
        'Oshawa - 04': {"lat": 43.876437, "lon": -78.848991},
        'Sterling South': {"lat": 42.542228, "lon": -83.041669},
        'Windsor - 02': {"lat": 42.286758, "lon": -83.016596}
    }
    loc = coordinates.get(plant_name, coordinates['Cambridge - 07'])
    date_str = target_date.strftime("%Y-%m-%d")
    url = "https://archive-api.open-meteo.com/v1/archive"
    params = {
        "latitude": loc["lat"], "longitude": loc["lon"],
        "start_date": date_str, "end_date": date_str,
        "daily": ["precipitation_sum"], "timezone": "America/New_York"
    }
    try:
        res = requests.get(url, params=params, timeout=5)
        if res.status_code == 200:
            p_sum = res.json()["daily"]["precipitation_sum"][0]
            return f"{round(p_sum, 1)} mm" if p_sum is not None else "0.0 mm"
    except: pass
    return "0.0 mm"

# Load base image layouts safely
try:
    if "Cambridge" in plant:
        left_path, right_path = "data/CambridgeCAD.png", "data/Cambridge.png"
    elif "Oshawa" in plant:
        left_path, right_path = "data/OshawaCAD.png", "data/Oshawa.png"
    elif "Sterling" in plant:
        left_path, right_path = "data/SterlingSouthCAD.png", "data/SterlingSouth.png"
    else:
        left_path, right_path = "data/WindsorCAD.png", "data/Windsor.png"

    left_img = Image.open(left_path).convert("RGB")
    right_img = Image.open(right_path).convert("RGB")
    
    DISPLAY_WIDTH = 600
    
    left_resized = left_img.resize((DISPLAY_WIDTH, int(left_img.height * (DISPLAY_WIDTH / left_img.width))))
    right_resized = right_img.resize((DISPLAY_WIDTH, int(right_img.height * (DISPLAY_WIDTH / right_img.width))))
except Exception as e:
    st.error(f"⚠️ Base asset missing inside data/ directory: {e}")
    st.stop()

left_display = left_resized.copy()
right_display = right_resized.copy()
draw_left = ImageDraw.Draw(left_display)
draw_right = ImageDraw.Draw(right_display)

excel_overlay_canvas = Image.new("RGBA", right_resized.size, (255, 255, 255, 0))
draw_excel = ImageDraw.Draw(excel_overlay_canvas)

# Loop and plot through all active session pins directly
for pt in st.session_state["new_pins_batch"]:
    x, y, custom_name = pt['x'], pt['y'], pt['name']
    
    draw_left.ellipse((x-6, y-6, x+6, y+6), fill="red")
    text_pos_left = (x + 10, y - 6)
    bbox_left = draw_left.textbbox(text_pos_left, custom_name)
    draw_left.rectangle((bbox_left[0]-4, bbox_left[1]-2, bbox_left[2]+4, bbox_left[3]+2), fill="white", outline="red", width=1)
    draw_left.text(text_pos_left, custom_name, fill="red")
    
    draw_right.ellipse((x-12, y-12, x+12, y+12), outline="cyan", width=3)
    draw_right.ellipse((x-3, y-3, x+3, y+3), fill="red")
    text_pos_right = (x + 16, y - 8)
    bbox_right = draw_right.textbbox(text_pos_right, custom_name)
    draw_right.rectangle((bbox_right[0]-4, bbox_right[1]-2, bbox_right[2]+4, bbox_right[3]+2), fill="#1A1A1A", outline="cyan", width=1)
    draw_right.text(text_pos_right, custom_name, fill="cyan")

    draw_excel.ellipse((x-12, y-12, x+12, y+12), outline="cyan", width=3)
    draw_excel.ellipse((x-3, y-3, x+3, y+3), fill="red")
    draw_excel.rectangle((bbox_right[0]-4, bbox_right[1]-2, bbox_right[2]+4, bbox_right[3]+2), fill="#1A1A1A", outline="cyan", width=1)
    draw_excel.text(text_pos_right, custom_name, fill="cyan")

# --- Restored Side-by-Side View Interface Layout ---
st.write("---")
col1, col2 = st.columns(2)
with col1:
    st.subheader("🗺️ Floor Map")
    
    #
